Added stellate morphology
pato-ontology/pato pull request #390
Opened 2021-02-16 14:29 UTC by shawntanzk

Fixes #382

2021-02-19 19:14 UTC, patrick-lloyd-ray commented on src/ontology/pato-edit.obo
> +def: "A cell morphology that inheres in neurons which have dendritic processes radiating for the cell body that forms a star-like shape" [ISBN:9780123973481]
Add full stop in definition.

2021-02-19 19:14 UTC, patrick-lloyd-ray reviewed
Small change -- looks good otherwise.

2021-04-07 15:49 UTC, dosumis requested changes
Minor text change

2021-04-07 15:49 UTC, dosumis commented on src/ontology/pato-edit.obo
> +def: "A cell morphology that inheres in neurons which have dendritic processes radiating for the cell body that forms a star-like shape." [ISBN:9780123973481]
> def: "A cell morphology that inheres in neurons which have dendritic processes radiating for the cell body that forms a star-like shape." [ISBN:9780123973481]

->
def: "A cell morphology that inheres in neurons that have dendritic processes radiating from the cell body forming a star-like shape." [ISBN:9780123973481]

2021-04-10 09:25 UTC, dosumis approved these changes

2021-04-12 17:52 UTC, patrick-lloyd-ray approved these changes

2021-04-12 17:56 UTC, merged