Added cell with bitufted dendrite morphology
pato-ontology/pato pull request #416
Opened 2021-06-07 14:06 UTC by shawntanzk

Fixes #415
related to #414

2021-06-07 16:54 UTC, patrick-lloyd-ray approved these changes

2021-06-09 18:28 UTC, shawntanzk commented
Note to self: change IRI - currently clashes with another PR

2021-06-11 09:32 UTC, dosumis requested changes
See comments here https://github.com/pato-ontology/pato/issues/415#issuecomment-859424441

Minor note: xref should not have space after colon (QC checks should really be catching that).

2021-06-29 19:20 UTC, cmungall commented on src/ontology/pato-edit.obo
> +name: cell with bitufted dendrite morphology
minor: this is named as is subclasses are cells. I think the implicit naming convention here dictates "bitufted dendrite cell morphology"

2021-08-02 15:50 UTC, patrick-lloyd-ray approved these changes

2021-11-03 16:43 UTC, dosumis approved these changes

2021-11-03 16:57 UTC, merged