Use dce:contributor instead of created_by & unify all attribution to ORCID
pato-ontology/pato pull request #457
Opened 2021-12-06 18:48 UTC by anitacaron

Fixes #281
Fixes #278

2021-12-07 08:51 UTC, matentzn requested changes
Can we also add the sparql check to look for unintended Annotation Properties in this PR?

2021-12-07 08:51 UTC, matentzn commented on src/ontology/pato-edit.obo
> +property_value: http://purl.org/dc/elements/1.1/contributor https://orcid.org/0000-0002-2061-091X
Let's use `http://purl.org/dc/terms/contributor`. What you have is not wrong, but this is the recommended one.

Check: https://dublincore.org/specifications/dublin-core/dcmi-terms/#contributor

2021-12-07 08:53 UTC, shawntanzk submitted a review, later dismissed

2021-12-08 14:14 UTC, matentzn commented on src/ontology/pato-edit.obo
> +property_value: http://purl.org/dc/elements/1.1/contributor https://orcid.org/0000-0002-2061-091X
Great!

2021-12-08 14:14 UTC, matentzn commented
See comment above:

> Can we also add the sparql check to look for unintended Annotation Properties in this PR?

2021-12-08 14:23 UTC, matentzn commented
Great! You still need to run `sh run.sh make update_repo` to apply the new test! Awesome thank you @anitacaron

2021-12-08 15:04 UTC, matentzn approved these changes
Great work! Ready for merging :)

2021-12-08 16:09 UTC, shawntanzk approved these changes

2021-12-08 16:24 UTC, merged