Make ratio the primary label
pato-ontology/pato pull request #556
Opened 2024-02-28 15:31 UTC by rays22

of
* PATO:0001470 ratio and child terms
* PATO:0040043 increased ratio
* PATO:0040042 decreased ratio

Also, improve the logical definitions of 'increased ratio' and 'decreased' by using EQs.

Resolve #555

2024-02-29 08:13 UTC, matentzn requested changes
I agree with the general changes at first glance but this needs @sbello @cmungall review.. (especially the renaming bit). 

I guess it comes down to the question if the new "proportionality to" is really the same in spirit as "ratio" - I hope so :)

2024-03-07 15:40 UTC, sbello commented
I see proportionality to used in the eqs for 4 MP terms (eg.abnormal lymph node cell ratio) these have eqs in the form
'has part' some 
('proportionality to' and ('characteristic of' some 'X') and (towards some Y) and ('has modifier' some abnormal))
I think ratio slots into this just fine. Most of the terms use ratio in the label already.

We aren't currently using increased or decreased child terms

The one thing that gives me pause is this part of the comment on the old term "Not all ratios measure proportionality, eg m/s measures velocity which is not a proportion in the sense defined above, it is a quality in its own right." But looking at the definition in both the old and new versions, I think the inclusion of 'the magnitude of another entity' excludes velocity since this involves a single entity.

I think the changes to the definition do not significantly alter the meaning of the term, so I am okay with this change.

2024-03-07 16:35 UTC, sbello submitted a review, later dismissed
I think this change is acceptable (longer comment in conversation)

2024-03-07 16:38 UTC, balhoff commented on src/ontology/pato-edit.obo
> +def: "A decreased quality inhering in a bearer by virtue of the bearer's decreased magnitude in proportion to the magnitude of anoter entity." [] {http://purl.org/dc/terms/contributor="https://orcid.
```suggestion
def: "A decreased quality inhering in a bearer by virtue of the bearer's decreased magnitude in proportion to the magnitude of another entity." [] {http://purl.org/dc/terms/contributor="https://orcid.org/0000-0001-8314-2140", http://purl.org/dc/terms/contributor="https://orcid.org/0000-0001-5208-3432"}
```

2024-03-07 16:38 UTC, balhoff commented on src/ontology/pato-edit.obo
> +def: "A decreased quality inhering in a bearer by virtue of the bearer's decreased magnitude in proportion to the magnitude of anoter entity." [] {http://purl.org/dc/terms/contributor="https://orcid.
Overall looks good, just a typo here.

2024-03-08 13:21 UTC, rays22 commented on src/ontology/pato-edit.obo
> +def: "A decreased quality inhering in a bearer by virtue of the bearer's decreased magnitude in proportion to the magnitude of anoter entity." [] {http://purl.org/dc/terms/contributor="https://orcid.
Thanks @balhoff for catching it!

2024-03-08 13:57 UTC, matentzn approved these changes

2024-03-14 14:36 UTC, ar-ibrahim commented
@rays22 Looks good. I just have a comment on whether the synonyms in the pattern should also reflect 'percentage' terms. For example terms like  [EFO:0007993 lymphocyte percentage of leukocytes](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0007993) describe a ratio relationship.

2024-03-14 16:13 UTC, rays22 commented
> @rays22 Looks good. I just have a comment on whether the synonyms in the pattern should also reflect 'percentage' terms. For example terms like [EFO:0007993 lymphocyte percentage of leukocytes](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0007993) describe a ratio relationship.

@ar-ibrahim , In the specific case of EFO:0007993, yes, using the PATIO 'ratio' quality would be appropriate based on this part of the textual definition: [... presented as a ratio, fraction, quotient or percentage.](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0007993)

2024-03-14 16:23 UTC, balhoff approved these changes

2024-03-14 16:25 UTC, merged